stages:
  - build
  - unit_tests
  - static_analysis
  - deploy_registry


build:
  stage: build
  tags:
    - geral
  script:
    - "npm install"
    
unit_tests:
  stage: unit_tests
  tags:
    - geral
  script:
    - echo -e "\n Testes unit치rios. \n"
    - "npm install && npm test"
   
sonarqube:
  stage: static_analysis
  tags:
    - geral
  script:
    - echo -e "\n An치lise est치tica do c칩digo. \n"
    - "./sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner"
  allow_failure: false

registry:
  stage: deploy_registry
  tags:
    - geral
  only:
    - master
  script:
    - "echo Deploy "
    - "docker login -u _json_key--password-stdin https://gcr.io < $GCLOUD_SERVICE_KEY"
    - "docker build -t gcr.io/$GCLOUD_PROJECT_ID/aplicacao-nodejs-exemplo1:v1.0 ."
    - "docker push gcr.io/$GCLOUD_PROJECT_ID/aplicacao-nodejs-exemplo1:v1.0"

