apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-exemplo
spec:
  replicas: 2
  selector:
    matchLabels:
      run: nodejs-exemplo
  template:
    metadata:
      labels:
        run: nodejs-exemplo
    spec:
      containers:
        - image: 'mendelev/nodejsapp:v1.0'
          name: nodejs-exemplo
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nodejs-exemplo
  name: nodejs-exemplo
spec:
  ports:
    - name: http
      nodePort: 31111
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: https
      port: 443
      protocol: TCP
  selector:
    run: nodejs-exemplo
  type: NodePort
---
null
